include(FetchContent)

FetchContent_Declare(
  openvdb
  GIT_REPOSITORY
    https://github.com/AcademySoftwareFoundation/openvdb.git
  GIT_TAG v12.1.0)

set(OPENVDB_BUILD_VDB_PRINT OFF CACHE STRING "" FORCE)
set(OPENVDB_BUILD_NANOVDB ON CACHE STRING "" FORCE)
set(NANOVDB_USE_OPENVDB ON CACHE STRING "" FORCE)
set(NANOVDB_USE_CUDA OFF CACHE STRING "" FORCE)
set(NANOVDB_USE_TBB ON CACHE STRING "" FORCE)
set(NANOVDB_USE_BLOSC OFF CACHE STRING "" FORCE)
set(NANOVDB_USE_ZLIB OFF CACHE STRING "" FORCE)
set(USE_NANOVDB ON CACHE STRING "" FORCE)

FetchContent_MakeAvailable(openvdb)


