include(FetchContent)

FetchContent_Declare(
  volk
  GIT_REPOSITORY https://github.com/zeux/volk.git
  GIT_TAG 1.3.270)

set(VOLK_INSTALL
    ON
    CACHE BOOL "" FORCE)
set(VOLK_PULL_IN_VULKAN
    ON
    CACHE BOOL "" FORCE)
set(VMA_BUILD_SAMPLES
    OFF
    CACHE BOOL "" FORCE)

# Set a suitable platform define to compile volk with.
if(CMAKE_SYSTEM_NAME STREQUAL Windows)
  set(VOLK_STATIC_DEFINES VK_USE_PLATFORM_WIN32_KHR)
elseif(CMAKE_SYSTEM_NAME STREQUAL Linux)
  set(VOLK_STATIC_DEFINES VK_USE_PLATFORM_XLIB_KHR)
  set(VOLK_STATIC_DEFINES VK_USE_PLATFORM_XCB_KHR)
elseif(CMAKE_SYSTEM_NAME STREQUAL Darwin)
  set(VOLK_STATIC_DEFINES VK_USE_PLATFORM_MACOS_MVK)
  set(VOLK_STATIC_DEFINES VK_USE_PLATFORM_METAL_EXT)
endif()

FetchContent_MakeAvailable(volk)

set(VOLK_INCLUDE_DIR ${volk_SOURCE_DIR} CACHE STRING "" FORCE)
set(VOLK_DEFINES ${VOLK_STATIC_DEFINES} CACHE STRING "" FORCE)



